const express = require("express");
const mongoose = require("mongoose");

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 3003;

// Start server

app.listen(PORT, () => {
  console.log("Server Listening on PORT:", PORT);
});

// Connect to DB

mongoose
  .connect(
    "mongodb+srv://arnas322:rtTh927RDbNH1Bhk@ecom.sft09eh.mongodb.net/?retryWrites=true&w=majority"
  )
  .then(() => {
    console.log("Connected to the database");
  })
  .catch((error) => {
    console.error("Error connecting to the database:", error);
  });

// import API's routes

const apiRoutes = require("./routes/api-products");
app.use("/api", apiRoutes);

const SingleProduct = require("./models/SingleProduct"); // Assuming your model is set up
const Product = require("./models/Product");

const axios = require("axios");

async function updateProductDetails() {
  try {
    const products = await Product.find({}, "PID"); // Fetch all products with only the PID field

    for (const product of products) {
      // const response = await axios.post(
      //   "https://api.accdistribution.net/v1/GetProduct",
      //   {
      //     request: {
      //       LicenseKey: "ccf5d1eb-f03b-42cc-b943-140a61db9897",
      //       Locale: "lt",
      //       Currency: "EUR",
      //       CompanyId: "_al",
      //       ProductId: product.PID,
      //     },
      //   }
      // );
      const productDetails = {
        RRP: [],
        Services: [
          {
            Id: 2,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "IBM Lietuva UAB",
            Email: "servLt@lt.ibm.com",
            Address: "Šeimyniškių g. 3",
            City: "Vilnius",
            Zip: "LT 09312",
            Country: "Lithuania",
            Phone: "+370 5 2786602",
            Url: "https://www.ibm.com/planetwide/lt/",
            ProductId: "398819",
          },
          {
            Id: 103,
            CountryId: "ee",
            SLAId: 9,
            SLA: "Other",
            Name: "IBM Eesti OU",
            Email: "ibm@ee.ibm.com",
            Address: "Toompuiestee 33 A ",
            City: "Tallinn ",
            Zip: "10149",
            Country: "Estonia",
            Phone: "+372 6 600 800 ",
            Url: "https://www.ibm.com/planetwide/ee/",
            ProductId: "398819",
          },
          {
            Id: 104,
            CountryId: "lv",
            SLAId: 9,
            SLA: "Other",
            Name: "IBM Latvia SIA",
            Email: "infolv@lv.ibm.com",
            Address: "Bauskas street 58A-12, 8th floor",
            City: "Riga",
            Zip: "LV 1004",
            Country: "Latvia",
            Phone: "+371 6707 0300",
            Url: "https://www.ibm.com/planetwide/lv/",
            ProductId: "398819",
          },
          {
            Id: 27,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "ATEA UAB",
            Email: "remontas@atea.lt˙",
            Address: "Brastos g. 14 LT-47185 Kaunas",
            City: "Kaunas",
            Zip: "LT 44150",
            Country: "Lithuania",
            Phone: "(8-37) 40 00 36",
            Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
            ProductId: "398819",
          },
          {
            Id: 238,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "ATEA UAB",
            Email: "remontas@atea.lt",
            Address: "J.Rutkausko g. 6 LT-05132 Vilnius",
            City: "Vilnius",
            Zip: "LT 05132 ",
            Country: "Lithuania",
            Phone: "(8-5) 239 78 36",
            Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
            ProductId: "398819",
          },
          {
            Id: 239,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "ATEA UAB",
            Email: "klaipeda@atea.lt",
            Address: "Pilies g. 8 LT-92294 Klaipėda",
            City: "Klaipėda",
            Zip: "LT 92294",
            Country: "Lithuania",
            Phone: "(8-46) 39 72 83",
            Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
            ProductId: "398819",
          },
          {
            Id: 240,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "ATEA UAB",
            Email: "alytus@atea.lt",
            Address: "Naujoji g. 3 LT-62119 Alytus",
            City: "Alytus",
            Zip: "LT 62119",
            Country: "Lithuania",
            Phone: "(8-315) 7 33 29",
            Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
            ProductId: "398819",
          },
          {
            Id: 241,
            CountryId: "lt",
            SLAId: 9,
            SLA: "Other",
            Name: "ATEA UAB",
            Email: "panevezys@atea.lt",
            Address: "Nemuno g. 73 LT-37355 Panevėžys",
            City: "Panevėžys",
            Zip: "LT 37355",
            Country: "Lithuania",
            Phone: "(8-45) 58 31 77",
            Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
            ProductId: "398819",
          },
        ],
        ProducerBids: [],
        PID: "398819",
        MPN: "21J8001FMX",
        EAN: "197529724590",
        Name: 'Lenovo ThinkBook  16p (Gen 4) IRH  Grey 16 " IPS WQXGA 2560 x 1600 Anti-glare Intel Core i7  i7-13700H SSD 16 GB SO-DIMM DDR5-5200 SSD 512 GB NVIDIA GeForce RTX 4060 GDDR6 8 GB Windows 11 Pro 802.11ax Bluetooth version 5.1 Keyboard language Nordic Keyboard backlit Warranty 24 month(s) Battery warranty 12 month(s)',
        Picture:
          "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad",
        Producer: {
          OId: "LV",
          Name: "Lenovo",
        },
        Price: {
          Value: 1551.22,
          OldValue: 1551.22,
          LatgaValue: 1557.01,
          LatgaOldValue: 1557.01,
          CurrencyCode: "EUR",
          SmartPoints: null,
          SpCampaignId: null,
          IsSaleout: false,
        },
        Stocks: [
          {
            WhId: "SALES",
            Amount: 3,
            ExpectedDate: null,
            AmountArriving: 0,
            AmountOrdered: 0,
            AmountOrderedArrivingDiff: 0,
            IsPreliminary: false,
          },
          {
            WhId: null,
            Amount: 0,
            ExpectedDate: "2024-02-15T00:00:00+02:00",
            AmountArriving: 4,
            AmountOrdered: 0,
            AmountOrderedArrivingDiff: 4,
            IsPreliminary: true,
          },
        ],
        Rent: false,
        ByOrder: false,
        Bundle: "",
        EOLSale: false,
        LatgaValue: 5.79,
        LatgaValueType: 1,
        Warranty: 24,
        Campaigns: [],
        Saleouts: [],
        Branches: [
          {
            OId: 1489,
            Name: "Nešiojamieji kompiuteriai",
          },
        ],
        Medias: [
          {
            Type: 3,
            Uri: "https://psref.lenovo.com/Detail/ThinkBook_16p_G4_IRH?M=21J8001FMX",
            OriginalUri: null,
            Order: 1,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad/original.jpg",
            Order: 1,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/9d13a0e29a695a4539e629b3736d377d",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/9d13a0e29a695a4539e629b3736d377d/original.jpg",
            Order: 2,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/74d4593b0616a5cecfa14eb984ce9396",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/74d4593b0616a5cecfa14eb984ce9396/original.jpg",
            Order: 3,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/ca0d532e3384826337f011c496aac377",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/ca0d532e3384826337f011c496aac377/original.jpg",
            Order: 4,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/47e3791f8210d2435dcfa3b60ee114f1",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/47e3791f8210d2435dcfa3b60ee114f1/original.jpg",
            Order: 5,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/546f7431131a08a5b271e86740eb9ab6",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/546f7431131a08a5b271e86740eb9ab6/original.jpg",
            Order: 6,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/f89e24eb30e68d824e723f1741fe27ab",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/f89e24eb30e68d824e723f1741fe27ab/original.jpg",
            Order: 7,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/2cd376c34920c8d9e07b52a18d1704b4",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/2cd376c34920c8d9e07b52a18d1704b4/original.jpg",
            Order: 8,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/181b8fd9aacc13766d51718d3feb27a3",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/181b8fd9aacc13766d51718d3feb27a3/original.jpg",
            Order: 9,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/25743eb451686aac15b0c5cb73b5a00e",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/25743eb451686aac15b0c5cb73b5a00e/original.jpg",
            Order: 10,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/62ad4de280bebea3ce2d4742326bca05",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/62ad4de280bebea3ce2d4742326bca05/original.jpg",
            Order: 11,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
          {
            Type: 0,
            Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/32d4e456d98ef620831bc0d180edccd7",
            OriginalUri:
              "https://www.blobs.lt/products/9/1/8/8/9/3/32d4e456d98ef620831bc0d180edccd7/original.jpg",
            Order: 12,
            Title: null,
            Description: null,
            LinkText: null,
            EEDocument: false,
            EELabel: false,
          },
        ],
        Parameters: [
          {
            ProductParameterId: 6109991,
            OId: 115549,
            GroupId: 188,
            ParameterName: "Gross depth (mm)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "354.60",
            MeasureId: 55,
            MeasureAbbr: "mm",
            MeasureFraction: 1000,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109992,
            OId: 115551,
            GroupId: 188,
            ParameterName: "Gross height (mm)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "19.90",
            MeasureId: 55,
            MeasureAbbr: "mm",
            MeasureFraction: 1000,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109993,
            OId: 108936,
            GroupId: 1,
            ParameterName: "Gross weight",
            ParameterGroupName: "Technical details",
            UseInDescription: false,
            Value: "3.872",
            MeasureId: 186,
            MeasureAbbr: "kg",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109994,
            OId: 115550,
            GroupId: 188,
            ParameterName: "Gross width (mm)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "255.00",
            MeasureId: 55,
            MeasureAbbr: "mm",
            MeasureFraction: 1000,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109995,
            OId: 108959,
            GroupId: 1,
            ParameterName: "Net weight",
            ParameterGroupName: "Technical details",
            UseInDescription: false,
            Value: "2.20",
            MeasureId: 186,
            MeasureAbbr: "kg",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109996,
            OId: 115523,
            GroupId: 188,
            ParameterName: "Packing quantity",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "1.00",
            MeasureId: 118,
            MeasureAbbr: "dalių",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109997,
            OId: 115542,
            GroupId: 188,
            ParameterName: "Paper/Pasteboard",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "1.53",
            MeasureId: 282,
            MeasureAbbr: "g",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109998,
            OId: 115541,
            GroupId: 188,
            ParameterName: "Plastic (No PET)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "0.14",
            MeasureId: 282,
            MeasureAbbr: "g",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6109999,
            OId: 115526,
            GroupId: 188,
            ParameterName: "Tare weight (kg)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "1.672",
            MeasureId: 186,
            MeasureAbbr: "kg",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110000,
            OId: 115527,
            GroupId: 188,
            ParameterName: "TI weight (kg)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "0.349",
            MeasureId: 186,
            MeasureAbbr: "kg",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110001,
            OId: 115521,
            GroupId: 188,
            ParameterName: "Volume (m3)",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "0.00",
            MeasureId: 43,
            MeasureAbbr: "m³",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110002,
            OId: 115534,
            GroupId: 188,
            ParameterName: "Classification of battery",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "CL126:NE:2016-12-09",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110003,
            OId: 115535,
            GroupId: 188,
            ParameterName: "Composition of battery",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "CL127:KT:2016-12-09",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110004,
            OId: 115536,
            GroupId: 188,
            ParameterName: "Type of battery",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "Accumulator",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110005,
            OId: 115537,
            GroupId: 188,
            ParameterName: "Embeeded battery",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "Yes",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110006,
            OId: 115538,
            GroupId: 188,
            ParameterName: "WEEE tax",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "Yes",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6110007,
            OId: 115539,
            GroupId: 188,
            ParameterName: "WEEE tax",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "CL109:2:2017-04-01",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6167793,
            OId: 115522,
            GroupId: 188,
            ParameterName: "Palette Qty",
            ParameterGroupName: "Package features",
            UseInDescription: false,
            Value: "374",
            MeasureId: 118,
            MeasureAbbr: "dalių",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175851,
            OId: 105948,
            GroupId: 6,
            ParameterName: "Įstrižainė",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "16",
            MeasureId: 9,
            MeasureAbbr: "col.",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175852,
            OId: 92096,
            GroupId: 6,
            ParameterName: "Ekrano paviršius",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "Anti-glare",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175853,
            OId: 92815,
            GroupId: 4,
            ParameterName: "Vidinės atminties tipas",
            ParameterGroupName: "Atmintis",
            UseInDescription: true,
            Value: "SO-DIMM DDR5-5200",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175854,
            OId: 95651,
            GroupId: 138,
            ParameterName: "Gaminio spalva",
            ParameterGroupName: "Dizainas",
            UseInDescription: true,
            Value: "Grey",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175855,
            OId: 96013,
            GroupId: 2,
            ParameterName: "Procesoriaus branduoliai",
            ParameterGroupName: "Procesorius",
            UseInDescription: false,
            Value: "14",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175856,
            OId: 96747,
            GroupId: 6,
            ParameterName: "HD tipas",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "WQXGA",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175857,
            OId: 97851,
            GroupId: 32,
            ParameterName: "Belaidžio ryšio standartai",
            ParameterGroupName: "Tinklas",
            UseInDescription: true,
            Value: "802.11ax",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175858,
            OId: 100438,
            GroupId: 2,
            ParameterName: "Procesorius",
            ParameterGroupName: "Procesorius",
            UseInDescription: true,
            Value: "Intel Core i7",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175859,
            OId: 100619,
            GroupId: 6,
            ParameterName: "Kamera",
            ParameterGroupName: "Ekranas",
            UseInDescription: false,
            Value: "FHD 1080p + IR Hybrid with Privacy Shutter",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175860,
            OId: 100824,
            GroupId: 83,
            ParameterName: "Įdiegta operacinė sistema",
            ParameterGroupName: "Programinė įranga",
            UseInDescription: true,
            Value: "Windows 11 Pro",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175861,
            OId: 106709,
            GroupId: 28,
            ParameterName: "Klaviatūros kalba",
            ParameterGroupName: "Klaviatūra",
            UseInDescription: true,
            Value: "Nordic",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175862,
            OId: 106846,
            GroupId: 11,
            ParameterName: "HDMI prievadų kiekis",
            ParameterGroupName: "Ryšys",
            UseInDescription: false,
            Value: "1",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175863,
            OId: 109866,
            GroupId: 11,
            ParameterName: "Pirštų antspaudų skaitytuvas",
            ParameterGroupName: "Ryšys",
            UseInDescription: false,
            Value:
              "Yes (Touch Style, Match-on-Chip, Integrated in Power Button)",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175864,
            OId: 110786,
            GroupId: 32,
            ParameterName: "„Bluetooth“ versija",
            ParameterGroupName: "Tinklas",
            UseInDescription: true,
            Value: "5.1",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175865,
            OId: 111918,
            GroupId: 5,
            ParameterName: "Optinio įrenginio tipas",
            ParameterGroupName: "Optinis diskas",
            UseInDescription: false,
            Value: "No Optical drive",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175866,
            OId: 113669,
            GroupId: 44,
            ParameterName: "Laikmena",
            ParameterGroupName: "Laikmenos",
            UseInDescription: true,
            Value: "SSD",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175867,
            OId: 114185,
            GroupId: 1,
            ParameterName: "Warranty",
            ParameterGroupName: "Technical details",
            UseInDescription: false,
            Value: " Depot ",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175868,
            OId: 114589,
            GroupId: 2,
            ParameterName: "Procesoriaus modelis",
            ParameterGroupName: "Procesorius",
            UseInDescription: true,
            Value: " i7-13700H",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175869,
            OId: 115464,
            GroupId: 138,
            ParameterName: "Gamintojo prekės modelio pavadinimas",
            ParameterGroupName: "Dizainas",
            UseInDescription: true,
            Value: "16p (Gen 4) IRH ",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175870,
            OId: 115465,
            GroupId: 138,
            ParameterName: "Gamintojo prekės serija",
            ParameterGroupName: "Dizainas",
            UseInDescription: true,
            Value: "ThinkBook ",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175871,
            OId: 101433,
            GroupId: 6,
            ParameterName: "Skydelio tipas",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "IPS",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175872,
            OId: 103613,
            GroupId: 134,
            ParameterName: "Akumuliatoriaus talpa (vat. val.)",
            ParameterGroupName: "Baterija",
            UseInDescription: false,
            Value: "80",
            MeasureId: 32,
            MeasureAbbr: "Wh",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175873,
            OId: 97936,
            GroupId: 2,
            ParameterName: "Procesoriaus paspartinimo dažnis",
            ParameterGroupName: "Procesorius",
            UseInDescription: false,
            Value: "P-core 5.0; E-core 3.7",
            MeasureId: 71,
            MeasureAbbr: "GHz",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175874,
            OId: 100256,
            GroupId: 6,
            ParameterName: "Ekranas",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "2560 x 1600",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175875,
            OId: 100150,
            GroupId: 1,
            ParameterName: "Warranty",
            ParameterGroupName: "Technical details",
            UseInDescription: true,
            Value: "24",
            MeasureId: 132,
            MeasureAbbr: "mėn.",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175876,
            OId: 115460,
            GroupId: 1,
            ParameterName: "Baterijos garantija",
            ParameterGroupName: "Technical details",
            UseInDescription: true,
            Value: "12",
            MeasureId: 132,
            MeasureAbbr: "mėn.",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175877,
            OId: 93621,
            GroupId: 4,
            ParameterName: "Vidinė atmintis",
            ParameterGroupName: "Atmintis",
            UseInDescription: true,
            Value: "16",
            MeasureId: 162,
            MeasureAbbr: "GB",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175878,
            OId: 96525,
            GroupId: 44,
            ParameterName: "Stacionaraus disko talpa",
            ParameterGroupName: "Laikmenos",
            UseInDescription: true,
            Value: "512",
            MeasureId: 162,
            MeasureAbbr: "GB",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175879,
            OId: 104063,
            GroupId: 44,
            ParameterName: "Bendroji laikmenos talpa",
            ParameterGroupName: "Laikmenos",
            UseInDescription: false,
            Value: "512",
            MeasureId: 162,
            MeasureAbbr: "GB",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175880,
            OId: 97735,
            GroupId: 32,
            ParameterName: "Belaidis ryšys",
            ParameterGroupName: "Tinklas",
            UseInDescription: false,
            Value: "Yes",
            MeasureId: 217,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175881,
            OId: 100479,
            GroupId: 6,
            ParameterName: "Jutiklinis ekranas",
            ParameterGroupName: "Ekranas",
            UseInDescription: true,
            Value: "No",
            MeasureId: 217,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175882,
            OId: 100889,
            GroupId: 32,
            ParameterName: "„Bluetooth“",
            ParameterGroupName: "Tinklas",
            UseInDescription: false,
            Value: "Yes",
            MeasureId: 217,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175883,
            OId: 103960,
            GroupId: 28,
            ParameterName: "Klaviatūros apšvietimas",
            ParameterGroupName: "Klaviatūra",
            UseInDescription: true,
            Value: "Yes",
            MeasureId: 217,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175884,
            OId: 110844,
            GroupId: 1,
            ParameterName: "Kitos savybės",
            ParameterGroupName: "Technical details",
            UseInDescription: false,
            Value:
              "1x Thunderbolt 4 / USB4 40Gbps (support data transfer, Power Delivery 3.0 and DisplayPort 1.4)",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175885,
            OId: 111005,
            GroupId: 11,
            ParameterName: "„SmartCard“ lizdas",
            ParameterGroupName: "Ryšys",
            UseInDescription: false,
            Value: "Smart Card Reader",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175886,
            OId: 104147,
            GroupId: 2,
            ParameterName: "Procesoriaus dažnis",
            ParameterGroupName: "Procesorius",
            UseInDescription: false,
            Value: "P-core 2.4; E-core 1.8",
            MeasureId: 71,
            MeasureAbbr: "GHz",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175887,
            OId: 98693,
            GroupId: 11,
            ParameterName: "USB 3.1 (3.1 Gen 2) Type-A prievadų kiekis",
            ParameterGroupName: "Ryšys",
            UseInDescription: false,
            Value: "2",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175888,
            OId: 92886,
            GroupId: 11,
            ParameterName: "USB 3.1 (3.1 Gen 2) Type-C prievadų kiekis",
            ParameterGroupName: "Ryšys",
            UseInDescription: false,
            Value: "1",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175889,
            OId: 94357,
            GroupId: 44,
            ParameterName: "Suderinamos atminties kortelės",
            ParameterGroupName: "Laikmenos",
            UseInDescription: false,
            Value: " SD card reader",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175890,
            OId: 95546,
            GroupId: 153,
            ParameterName: "Diskrečiosios grafikos adapterio tipas",
            ParameterGroupName: "Grafika",
            UseInDescription: true,
            Value: "NVIDIA GeForce RTX 4060",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175891,
            OId: 104285,
            GroupId: 153,
            ParameterName: "Diskrečiosios grafikos adapterio atmintis",
            ParameterGroupName: "Grafika",
            UseInDescription: true,
            Value: "8",
            MeasureId: 162,
            MeasureAbbr: "GB",
            MeasureFraction: 1,
            SpecificationType: "None",
          },
          {
            ProductParameterId: 6175892,
            OId: 106067,
            GroupId: 153,
            ParameterName: "Diskrečiosios grafikos atminties tipas",
            ParameterGroupName: "Grafika",
            UseInDescription: true,
            Value: "GDDR6",
            MeasureId: 26,
            MeasureAbbr: null,
            MeasureFraction: 1,
            SpecificationType: "None",
          },
        ],
        CreatedAt: "2023-04-25T13:14:08.347+03:00",
        UpdatedAt: "2024-01-31T02:04:14.3366667+02:00",
        StocksUpdatedAt: "2024-02-03T04:36:03.3826083+02:00",
        PricesUpdatedAt: "2024-02-03T04:36:03.3826083+02:00",
        Reserve: null,
        Reserves: [],
        Attributes: [],
        CountryOfOrigin: "CN",
        IntraCode: "84713000",
        RelatedProducts: [],
      };

      // Update the product in the database with the new details
      await SingleProduct.findOneAndUpdate(
        { PID: product.PID },
        productDetails,
        {
          new: true,
        }
      );
    }

    console.log("All products have been updated successfully");
  } catch (error) {
    console.error("Error updating product details:", error);
  }
}

const pid = "398819"; // Set the PID of the product you want to update

async function updateSingleProductDetail(pid) {
  try {
    // const response = await axios.get(`https://api.example.com/getProduct/${pid}`);
    const productDetails = {
      RRP: [],
      Services: [
        {
          Id: 2,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "IBM Lietuva UAB",
          Email: "servLt@lt.ibm.com",
          Address: "Šeimyniškių g. 3",
          City: "Vilnius",
          Zip: "LT 09312",
          Country: "Lithuania",
          Phone: "+370 5 2786602",
          Url: "https://www.ibm.com/planetwide/lt/",
          ProductId: "398819",
        },
        {
          Id: 103,
          CountryId: "ee",
          SLAId: 9,
          SLA: "Other",
          Name: "IBM Eesti OU",
          Email: "ibm@ee.ibm.com",
          Address: "Toompuiestee 33 A ",
          City: "Tallinn ",
          Zip: "10149",
          Country: "Estonia",
          Phone: "+372 6 600 800 ",
          Url: "https://www.ibm.com/planetwide/ee/",
          ProductId: "398819",
        },
        {
          Id: 104,
          CountryId: "lv",
          SLAId: 9,
          SLA: "Other",
          Name: "IBM Latvia SIA",
          Email: "infolv@lv.ibm.com",
          Address: "Bauskas street 58A-12, 8th floor",
          City: "Riga",
          Zip: "LV 1004",
          Country: "Latvia",
          Phone: "+371 6707 0300",
          Url: "https://www.ibm.com/planetwide/lv/",
          ProductId: "398819",
        },
        {
          Id: 27,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "ATEA UAB",
          Email: "remontas@atea.lt˙",
          Address: "Brastos g. 14 LT-47185 Kaunas",
          City: "Kaunas",
          Zip: "LT 44150",
          Country: "Lithuania",
          Phone: "(8-37) 40 00 36",
          Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
          ProductId: "398819",
        },
        {
          Id: 238,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "ATEA UAB",
          Email: "remontas@atea.lt",
          Address: "J.Rutkausko g. 6 LT-05132 Vilnius",
          City: "Vilnius",
          Zip: "LT 05132 ",
          Country: "Lithuania",
          Phone: "(8-5) 239 78 36",
          Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
          ProductId: "398819",
        },
        {
          Id: 239,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "ATEA UAB",
          Email: "klaipeda@atea.lt",
          Address: "Pilies g. 8 LT-92294 Klaipėda",
          City: "Klaipėda",
          Zip: "LT 92294",
          Country: "Lithuania",
          Phone: "(8-46) 39 72 83",
          Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
          ProductId: "398819",
        },
        {
          Id: 240,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "ATEA UAB",
          Email: "alytus@atea.lt",
          Address: "Naujoji g. 3 LT-62119 Alytus",
          City: "Alytus",
          Zip: "LT 62119",
          Country: "Lithuania",
          Phone: "(8-315) 7 33 29",
          Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
          ProductId: "398819",
        },
        {
          Id: 241,
          CountryId: "lt",
          SLAId: 9,
          SLA: "Other",
          Name: "ATEA UAB",
          Email: "panevezys@atea.lt",
          Address: "Nemuno g. 73 LT-37355 Panevėžys",
          City: "Panevėžys",
          Zip: "LT 37355",
          Country: "Lithuania",
          Phone: "(8-45) 58 31 77",
          Url: "https://www.atea.lt/paslaugos/it-irangos-remontas/",
          ProductId: "398819",
        },
      ],
      ProducerBids: [],
      PID: "398819",
      MPN: "21J8001FMX",
      EAN: "197529724590",
      Name: 'Lenovo ThinkBook  16p (Gen 4) IRH  Grey 16 " IPS WQXGA 2560 x 1600 Anti-glare Intel Core i7  i7-13700H SSD 16 GB SO-DIMM DDR5-5200 SSD 512 GB NVIDIA GeForce RTX 4060 GDDR6 8 GB Windows 11 Pro 802.11ax Bluetooth version 5.1 Keyboard language Nordic Keyboard backlit Warranty 24 month(s) Battery warranty 12 month(s)',
      Picture:
        "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad",
      Producer: {
        OId: "LV",
        Name: "Lenovo",
      },
      Price: {
        Value: 1551.22,
        OldValue: 1551.22,
        LatgaValue: 1557.01,
        LatgaOldValue: 1557.01,
        CurrencyCode: "EUR",
        SmartPoints: null,
        SpCampaignId: null,
        IsSaleout: false,
      },
      Stocks: [
        {
          WhId: "SALES",
          Amount: 3,
          ExpectedDate: null,
          AmountArriving: 0,
          AmountOrdered: 0,
          AmountOrderedArrivingDiff: 0,
          IsPreliminary: false,
        },
        {
          WhId: null,
          Amount: 0,
          ExpectedDate: "2024-02-15T00:00:00+02:00",
          AmountArriving: 4,
          AmountOrdered: 0,
          AmountOrderedArrivingDiff: 4,
          IsPreliminary: true,
        },
      ],
      Rent: false,
      ByOrder: false,
      Bundle: "",
      EOLSale: false,
      LatgaValue: 5.79,
      LatgaValueType: 1,
      Warranty: 24,
      Campaigns: [],
      Saleouts: [],
      Branches: [
        {
          OId: 1489,
          Name: "Nešiojamieji kompiuteriai",
        },
      ],
      Medias: [
        {
          Type: 3,
          Uri: "https://psref.lenovo.com/Detail/ThinkBook_16p_G4_IRH?M=21J8001FMX",
          OriginalUri: null,
          Order: 1,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/ecfa489b86a1097028eca814390829ad/original.jpg",
          Order: 1,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/9d13a0e29a695a4539e629b3736d377d",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/9d13a0e29a695a4539e629b3736d377d/original.jpg",
          Order: 2,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/74d4593b0616a5cecfa14eb984ce9396",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/74d4593b0616a5cecfa14eb984ce9396/original.jpg",
          Order: 3,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/ca0d532e3384826337f011c496aac377",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/ca0d532e3384826337f011c496aac377/original.jpg",
          Order: 4,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/47e3791f8210d2435dcfa3b60ee114f1",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/47e3791f8210d2435dcfa3b60ee114f1/original.jpg",
          Order: 5,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/546f7431131a08a5b271e86740eb9ab6",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/546f7431131a08a5b271e86740eb9ab6/original.jpg",
          Order: 6,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/f89e24eb30e68d824e723f1741fe27ab",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/f89e24eb30e68d824e723f1741fe27ab/original.jpg",
          Order: 7,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/2cd376c34920c8d9e07b52a18d1704b4",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/2cd376c34920c8d9e07b52a18d1704b4/original.jpg",
          Order: 8,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/181b8fd9aacc13766d51718d3feb27a3",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/181b8fd9aacc13766d51718d3feb27a3/original.jpg",
          Order: 9,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/25743eb451686aac15b0c5cb73b5a00e",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/25743eb451686aac15b0c5cb73b5a00e/original.jpg",
          Order: 10,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/62ad4de280bebea3ce2d4742326bca05",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/62ad4de280bebea3ce2d4742326bca05/original.jpg",
          Order: 11,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
        {
          Type: 0,
          Uri: "https://www.blobs.lt/products/9/1/8/8/9/3/32d4e456d98ef620831bc0d180edccd7",
          OriginalUri:
            "https://www.blobs.lt/products/9/1/8/8/9/3/32d4e456d98ef620831bc0d180edccd7/original.jpg",
          Order: 12,
          Title: null,
          Description: null,
          LinkText: null,
          EEDocument: false,
          EELabel: false,
        },
      ],
      Parameters: [
        {
          ProductParameterId: 6109991,
          OId: 115549,
          GroupId: 188,
          ParameterName: "Gross depth (mm)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "354.60",
          MeasureId: 55,
          MeasureAbbr: "mm",
          MeasureFraction: 1000,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109992,
          OId: 115551,
          GroupId: 188,
          ParameterName: "Gross height (mm)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "19.90",
          MeasureId: 55,
          MeasureAbbr: "mm",
          MeasureFraction: 1000,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109993,
          OId: 108936,
          GroupId: 1,
          ParameterName: "Gross weight",
          ParameterGroupName: "Technical details",
          UseInDescription: false,
          Value: "3.872",
          MeasureId: 186,
          MeasureAbbr: "kg",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109994,
          OId: 115550,
          GroupId: 188,
          ParameterName: "Gross width (mm)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "255.00",
          MeasureId: 55,
          MeasureAbbr: "mm",
          MeasureFraction: 1000,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109995,
          OId: 108959,
          GroupId: 1,
          ParameterName: "Net weight",
          ParameterGroupName: "Technical details",
          UseInDescription: false,
          Value: "2.20",
          MeasureId: 186,
          MeasureAbbr: "kg",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109996,
          OId: 115523,
          GroupId: 188,
          ParameterName: "Packing quantity",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "1.00",
          MeasureId: 118,
          MeasureAbbr: "dalių",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109997,
          OId: 115542,
          GroupId: 188,
          ParameterName: "Paper/Pasteboard",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "1.53",
          MeasureId: 282,
          MeasureAbbr: "g",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109998,
          OId: 115541,
          GroupId: 188,
          ParameterName: "Plastic (No PET)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "0.14",
          MeasureId: 282,
          MeasureAbbr: "g",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6109999,
          OId: 115526,
          GroupId: 188,
          ParameterName: "Tare weight (kg)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "1.672",
          MeasureId: 186,
          MeasureAbbr: "kg",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110000,
          OId: 115527,
          GroupId: 188,
          ParameterName: "TI weight (kg)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "0.349",
          MeasureId: 186,
          MeasureAbbr: "kg",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110001,
          OId: 115521,
          GroupId: 188,
          ParameterName: "Volume (m3)",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "0.00",
          MeasureId: 43,
          MeasureAbbr: "m³",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110002,
          OId: 115534,
          GroupId: 188,
          ParameterName: "Classification of battery",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "CL126:NE:2016-12-09",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110003,
          OId: 115535,
          GroupId: 188,
          ParameterName: "Composition of battery",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "CL127:KT:2016-12-09",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110004,
          OId: 115536,
          GroupId: 188,
          ParameterName: "Type of battery",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "Accumulator",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110005,
          OId: 115537,
          GroupId: 188,
          ParameterName: "Embeeded battery",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "Yes",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110006,
          OId: 115538,
          GroupId: 188,
          ParameterName: "WEEE tax",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "Yes",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6110007,
          OId: 115539,
          GroupId: 188,
          ParameterName: "WEEE tax",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "CL109:2:2017-04-01",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6167793,
          OId: 115522,
          GroupId: 188,
          ParameterName: "Palette Qty",
          ParameterGroupName: "Package features",
          UseInDescription: false,
          Value: "374",
          MeasureId: 118,
          MeasureAbbr: "dalių",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175851,
          OId: 105948,
          GroupId: 6,
          ParameterName: "Įstrižainė",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "16",
          MeasureId: 9,
          MeasureAbbr: "col.",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175852,
          OId: 92096,
          GroupId: 6,
          ParameterName: "Ekrano paviršius",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "Anti-glare",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175853,
          OId: 92815,
          GroupId: 4,
          ParameterName: "Vidinės atminties tipas",
          ParameterGroupName: "Atmintis",
          UseInDescription: true,
          Value: "SO-DIMM DDR5-5200",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175854,
          OId: 95651,
          GroupId: 138,
          ParameterName: "Gaminio spalva",
          ParameterGroupName: "Dizainas",
          UseInDescription: true,
          Value: "Grey",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175855,
          OId: 96013,
          GroupId: 2,
          ParameterName: "Procesoriaus branduoliai",
          ParameterGroupName: "Procesorius",
          UseInDescription: false,
          Value: "14",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175856,
          OId: 96747,
          GroupId: 6,
          ParameterName: "HD tipas",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "WQXGA",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175857,
          OId: 97851,
          GroupId: 32,
          ParameterName: "Belaidžio ryšio standartai",
          ParameterGroupName: "Tinklas",
          UseInDescription: true,
          Value: "802.11ax",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175858,
          OId: 100438,
          GroupId: 2,
          ParameterName: "Procesorius",
          ParameterGroupName: "Procesorius",
          UseInDescription: true,
          Value: "Intel Core i7",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175859,
          OId: 100619,
          GroupId: 6,
          ParameterName: "Kamera",
          ParameterGroupName: "Ekranas",
          UseInDescription: false,
          Value: "FHD 1080p + IR Hybrid with Privacy Shutter",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175860,
          OId: 100824,
          GroupId: 83,
          ParameterName: "Įdiegta operacinė sistema",
          ParameterGroupName: "Programinė įranga",
          UseInDescription: true,
          Value: "Windows 11 Pro",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175861,
          OId: 106709,
          GroupId: 28,
          ParameterName: "Klaviatūros kalba",
          ParameterGroupName: "Klaviatūra",
          UseInDescription: true,
          Value: "Nordic",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175862,
          OId: 106846,
          GroupId: 11,
          ParameterName: "HDMI prievadų kiekis",
          ParameterGroupName: "Ryšys",
          UseInDescription: false,
          Value: "1",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175863,
          OId: 109866,
          GroupId: 11,
          ParameterName: "Pirštų antspaudų skaitytuvas",
          ParameterGroupName: "Ryšys",
          UseInDescription: false,
          Value: "Yes (Touch Style, Match-on-Chip, Integrated in Power Button)",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175864,
          OId: 110786,
          GroupId: 32,
          ParameterName: "„Bluetooth“ versija",
          ParameterGroupName: "Tinklas",
          UseInDescription: true,
          Value: "5.1",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175865,
          OId: 111918,
          GroupId: 5,
          ParameterName: "Optinio įrenginio tipas",
          ParameterGroupName: "Optinis diskas",
          UseInDescription: false,
          Value: "No Optical drive",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175866,
          OId: 113669,
          GroupId: 44,
          ParameterName: "Laikmena",
          ParameterGroupName: "Laikmenos",
          UseInDescription: true,
          Value: "SSD",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175867,
          OId: 114185,
          GroupId: 1,
          ParameterName: "Warranty",
          ParameterGroupName: "Technical details",
          UseInDescription: false,
          Value: " Depot ",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175868,
          OId: 114589,
          GroupId: 2,
          ParameterName: "Procesoriaus modelis",
          ParameterGroupName: "Procesorius",
          UseInDescription: true,
          Value: " i7-13700H",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175869,
          OId: 115464,
          GroupId: 138,
          ParameterName: "Gamintojo prekės modelio pavadinimas",
          ParameterGroupName: "Dizainas",
          UseInDescription: true,
          Value: "16p (Gen 4) IRH ",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175870,
          OId: 115465,
          GroupId: 138,
          ParameterName: "Gamintojo prekės serija",
          ParameterGroupName: "Dizainas",
          UseInDescription: true,
          Value: "ThinkBook ",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175871,
          OId: 101433,
          GroupId: 6,
          ParameterName: "Skydelio tipas",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "IPS",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175872,
          OId: 103613,
          GroupId: 134,
          ParameterName: "Akumuliatoriaus talpa (vat. val.)",
          ParameterGroupName: "Baterija",
          UseInDescription: false,
          Value: "80",
          MeasureId: 32,
          MeasureAbbr: "Wh",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175873,
          OId: 97936,
          GroupId: 2,
          ParameterName: "Procesoriaus paspartinimo dažnis",
          ParameterGroupName: "Procesorius",
          UseInDescription: false,
          Value: "P-core 5.0; E-core 3.7",
          MeasureId: 71,
          MeasureAbbr: "GHz",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175874,
          OId: 100256,
          GroupId: 6,
          ParameterName: "Ekranas",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "2560 x 1600",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175875,
          OId: 100150,
          GroupId: 1,
          ParameterName: "Warranty",
          ParameterGroupName: "Technical details",
          UseInDescription: true,
          Value: "24",
          MeasureId: 132,
          MeasureAbbr: "mėn.",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175876,
          OId: 115460,
          GroupId: 1,
          ParameterName: "Baterijos garantija",
          ParameterGroupName: "Technical details",
          UseInDescription: true,
          Value: "12",
          MeasureId: 132,
          MeasureAbbr: "mėn.",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175877,
          OId: 93621,
          GroupId: 4,
          ParameterName: "Vidinė atmintis",
          ParameterGroupName: "Atmintis",
          UseInDescription: true,
          Value: "16",
          MeasureId: 162,
          MeasureAbbr: "GB",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175878,
          OId: 96525,
          GroupId: 44,
          ParameterName: "Stacionaraus disko talpa",
          ParameterGroupName: "Laikmenos",
          UseInDescription: true,
          Value: "512",
          MeasureId: 162,
          MeasureAbbr: "GB",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175879,
          OId: 104063,
          GroupId: 44,
          ParameterName: "Bendroji laikmenos talpa",
          ParameterGroupName: "Laikmenos",
          UseInDescription: false,
          Value: "512",
          MeasureId: 162,
          MeasureAbbr: "GB",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175880,
          OId: 97735,
          GroupId: 32,
          ParameterName: "Belaidis ryšys",
          ParameterGroupName: "Tinklas",
          UseInDescription: false,
          Value: "Yes",
          MeasureId: 217,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175881,
          OId: 100479,
          GroupId: 6,
          ParameterName: "Jutiklinis ekranas",
          ParameterGroupName: "Ekranas",
          UseInDescription: true,
          Value: "No",
          MeasureId: 217,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175882,
          OId: 100889,
          GroupId: 32,
          ParameterName: "„Bluetooth“",
          ParameterGroupName: "Tinklas",
          UseInDescription: false,
          Value: "Yes",
          MeasureId: 217,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175883,
          OId: 103960,
          GroupId: 28,
          ParameterName: "Klaviatūros apšvietimas",
          ParameterGroupName: "Klaviatūra",
          UseInDescription: true,
          Value: "Yes",
          MeasureId: 217,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175884,
          OId: 110844,
          GroupId: 1,
          ParameterName: "Kitos savybės",
          ParameterGroupName: "Technical details",
          UseInDescription: false,
          Value:
            "1x Thunderbolt 4 / USB4 40Gbps (support data transfer, Power Delivery 3.0 and DisplayPort 1.4)",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175885,
          OId: 111005,
          GroupId: 11,
          ParameterName: "„SmartCard“ lizdas",
          ParameterGroupName: "Ryšys",
          UseInDescription: false,
          Value: "Smart Card Reader",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175886,
          OId: 104147,
          GroupId: 2,
          ParameterName: "Procesoriaus dažnis",
          ParameterGroupName: "Procesorius",
          UseInDescription: false,
          Value: "P-core 2.4; E-core 1.8",
          MeasureId: 71,
          MeasureAbbr: "GHz",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175887,
          OId: 98693,
          GroupId: 11,
          ParameterName: "USB 3.1 (3.1 Gen 2) Type-A prievadų kiekis",
          ParameterGroupName: "Ryšys",
          UseInDescription: false,
          Value: "2",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175888,
          OId: 92886,
          GroupId: 11,
          ParameterName: "USB 3.1 (3.1 Gen 2) Type-C prievadų kiekis",
          ParameterGroupName: "Ryšys",
          UseInDescription: false,
          Value: "1",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175889,
          OId: 94357,
          GroupId: 44,
          ParameterName: "Suderinamos atminties kortelės",
          ParameterGroupName: "Laikmenos",
          UseInDescription: false,
          Value: " SD card reader",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175890,
          OId: 95546,
          GroupId: 153,
          ParameterName: "Diskrečiosios grafikos adapterio tipas",
          ParameterGroupName: "Grafika",
          UseInDescription: true,
          Value: "NVIDIA GeForce RTX 4060",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175891,
          OId: 104285,
          GroupId: 153,
          ParameterName: "Diskrečiosios grafikos adapterio atmintis",
          ParameterGroupName: "Grafika",
          UseInDescription: true,
          Value: "8",
          MeasureId: 162,
          MeasureAbbr: "GB",
          MeasureFraction: 1,
          SpecificationType: "None",
        },
        {
          ProductParameterId: 6175892,
          OId: 106067,
          GroupId: 153,
          ParameterName: "Diskrečiosios grafikos atminties tipas",
          ParameterGroupName: "Grafika",
          UseInDescription: true,
          Value: "GDDR6",
          MeasureId: 26,
          MeasureAbbr: null,
          MeasureFraction: 1,
          SpecificationType: "None",
        },
      ],
      CreatedAt: "2023-04-25T13:14:08.347+03:00",
      UpdatedAt: "2024-01-31T02:04:14.3366667+02:00",
      StocksUpdatedAt: "2024-02-03T04:36:03.3826083+02:00",
      PricesUpdatedAt: "2024-02-03T04:36:03.3826083+02:00",
      Reserve: null,
      Reserves: [],
      Attributes: [],
      CountryOfOrigin: "CN",
      IntraCode: "84713000",
      RelatedProducts: [],
    };

    // Update the single product in the SingleProduct model with the new details
    await SingleProduct.create(productDetails);

    console.log(`Product details updated for PID: ${pid}`);
  } catch (error) {
    console.error(`Error updating product details for PID: ${pid}:`, error);
  }
}

// updateSingleProductDetail(pid);

updateProductDetails();
